trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Carnegie.ApplicationInsights.Common/*

resources:
  repositories:
  - repository: templates
    name: azdo-pipeline-templates
    type: git 
    ref: master
    
variables:
  projectFolder: 'Carnegie.ApplicationInsights.Common*'
  project: '$(projectFolder)/*.csproj'
  testProjects: '$(projectFolder)/*.Tests.csproj'
  buildConfiguration: 'Release'

pool: 'Default'

steps:
- template: steps/dotnetcore/sonarqube-prepare.yml@templates
  parameters:
    sonarProjectName: 'Carnegie.ApplicationInsights'
    sonarProjectKey: 'CarnegieIT_Carnegie.ApplicationInsights'

- template: steps/dotnetcore/build-and-test.yml@templates
  parameters:
    projects: '$(project)'
    testProjects: '$(testProjects)'
    buildConfiguration: '$(buildConfiguration)'

- template: steps/dotnetcore/sonarqube-analyze.yml@templates

- template: steps/dotnetcore/publish-nuget.yml@templates
  parameters:
    projects: '$(project)'