# Pipeline for building and pushing the Carnegie.ApplicationInsights.MassTransit nuget package.
# The version number must be updated in the project file to avoid version conflicts in the "Nuget push" task.
# YAML docs: https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      # Variables not supported here (https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#paths)
      - Carnegie.ApplicationInsights.MassTransit/*

variables:
  projectFolder: 'Carnegie.ApplicationInsights.MassTransit'
  project: '$(projectFolder)/**.csproj'
  buildConfiguration: 'Release'
  suffix: $[replace(variables['build.sourcebranchname'], '_', '-')]
  ${{ if ne( variables['Build.SourceBranchName'], 'master') }}: 
    label: -$(suffix) 
  ${{ if eq( variables['Build.SourceBranchName'], 'master') }}: 
    label: ''

pool: 'tfssetup'


steps:

- template: steps/dotnetcore/semantic-versioning.yml@templates
  parameters:
    projectName: 'Carnegie.ApplicationInsights.MassTransit'
    label: $(label)

- task: UseDotNet@2
  displayName: 'Use dotnet 6.x'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore...'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    projects: '$(project)'
    vstsFeed: 'd2ddfc16-5988-4c23-966e-3127e0b2d886'
    includeNuGetOrg: false

- task: DotNetCoreCLI@2
  displayName: 'Build...'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack...'
  inputs:
    command: 'pack'
    packagesToPack: '$(project)'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  displayName: 'Nuget push...'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '/d2ddfc16-5988-4c23-966e-3127e0b2d886'